### ISSUE TITLE
Spongepowered Mixin Crash on 1.20.1 Forge on Launch

### ISSUE THREAD

**Issue by Mqony** [Keksuccino/ModernWorldCreation#13]
Crashes upon game start, solved when I removed it
[crash-2024-08-08_19.14.32-client.txt](https://github.com/user-attachments/files/16555095/crash-2024-08-08_19.14.32-client.txt)

**Comment by Keksuccino** [comment]
Modern World Creation isn't even available for 1.20.1, ma guy. Of course it crashes.
